import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LoginOutBtn from "./LoginOutBtn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <div className="navbar">
        <Link href="/" className="logo">
          Appleforum
        </Link>
        <Link href="/list">List</Link>
        <Link href="/register">Register</Link>
        <Link href="/write">Write</Link>
        {session ? (
          <>
            {session.user.name} 님 
            <LoginOutBtn />
          </>
        ) : (
          <LoginBtn />
        )}
      </div>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
